libp2p/go-libp2p-peerstore

- peerstore.go
- peerstore_test.go
This allows us to overwrite known protocols and remove potentially
unwanted ones during a full knowledge update. The current AddProtocol
just appends to the existing set.
> Add SetProtocols method to peerstore

- peerinfo.go
- peerinfo_test.go
Follow-up to 968d9c91499150d85b260b7e1e58fcd5b0dd0c32
Also: Allow for parsing otherwise empty /ipfs addrs, improve tests
> Add func to construct /ipfs addrs from PeerInfo

- .travis.yml
- codecov.yml
This also switches from goveralls to codecov.
> Update Travis CI to use standard test script and go 1.9.x.

- .travis.yml
- addr_manager.go
- peerstore_test.go
* Completely free memory related to subscriptions when all subscribers go away.
* Completely free peer address records when they all expire.
* Don't copy the *entire* subscription array when unsubscribing from a peer
address stream.
> more effectively free memory

- addr_manager.go
Addresses https://github.com/libp2p/go-libp2p-peerstore/issues/15 by replacing `map[string]expiringAddr` with `[]expiringAddr`, and changes the name of the type `addrSet` to `addrSlice`, since the latter term would now be a more accurate description.
When I profile it on my machine, on an idle ipfs, this reduces the memory usage of `AddAddrs` from ~45% of the total to ~15%.
> Memory usage

- addr_manager.go
This technically worked, but was extremely misleading.
> we no longer use maps

- interface.go
- package.json
- pstoreds/addr_book.go
- pstoreds/ds_test.go
- pstoreds/keybook.go
- pstoreds/metadata.go
- pstoreds/peerstore.go
- pstoremem/metadata.go
All pretty standard, except that the `PeerMetadata` accepts values of wildcard type (`interface{}`), which now need to be serialised and deserialised. 
Took the simple path and used gob, which requires registering non-basic types beforehand, like `map[string]struct{}`, used by the `*Protocol()` methods on `Peerstore`.
However, given the public interface, it's possible for callers to use custom types (e.g. storing custom structs as metadata), which will need to be enlisted with the serialiser. I considered different options:
1. Dynamically registering types on `Put()` and keeping a type cache to avoid duplicate registrations (even if they are harmless), but this doesn't work on restart, as the user may `Get()` values for a type that hasn't been registered via `Put()` yet.
2. Adding a …
> Datastore-backed implementations of KeyBook and PeerMetadata

- pstoremem/addr_book.go
1. Revert to the memory heavy, allocation light in-memory representation. We switched to arrays to save memory but, unfortunately, that started killing us on allocations.
2. Add a once-per-hour GC cycle. We GC when we *read* a peer's addresses but we don't do that very often.
Now, there *are* better ways to GC and we should probably use them. However, this is probably a decent stop-gap.
> reduce allocations and garbage collect the in-memory peerstore

- package.json
- pstoreds/keybook.go
- pstoremem/keybook.go
- test/keybook_suite.go
This is a "more correct" API and we might as well fix this before it becomes used all over the place. The new API returns ErrNoPublicKey when there is no inlined key.
This *also* fixes a bug where the datastore-backed keystore would panic if `ExtractPublicKey` returned `nil, nil`.
> update to match new ExtractPublicKey API

- .travis.yml
- test/keybook_suite.go
RandTestKeyPair uses RSA keys but we now forbid any RSA key under 512 bits.
> fix the inline key test

- peerinfo.go
- peerinfo_test.go
The issue is [here](https://github.com/libp2p/go-libp2p/issues/393). Now `json.Marshal` can take value or pointer.
> PeerInfo UnMarshal Error #393

- README.md
Looks like the full path is case-sensitive.
> README: Update contributing guideline linkrot.

- test/addr_book_suite.go
See https://github.com/libp2p/go-libp2p-identify/issues/2#issuecomment-456794446
> Add unit test to verify AddAddr doesn't shorten TTL

- peerinfo.go
Currently when logged, this type spews raw binary from the ID field (which causes havoc on terminals and confuses text consumers). The goal is similar to https://github.com/libp2p/go-libp2p-peer/pull/47.
> Implement fmt.Stringer for PeerInfo

- interface.go
Unfortunately, services like the DHT are slow enough that we can forget addresses before we successfully dial.
> keep temp addresses for 2 minutes

- peerstore.go
- pstoremem/metadata.go
> optimize peerstore memory

- pstoremem/addr_book.go
Fixes the panic in #75 and also reworks the gc logic to happen in the background with a periodic process.
Closes #75
> don't delete under the read lock

- interface.go
- peerstore.go
- pstoreds/peerstore.go
- pstoreds/protobook.go
- pstoremem/addr_book.go
- pstoremem/peerstore.go
- pstoremem/protobook.go
Quick attempt to remove the global lock on addr map. Should reduce lock contention under high load. Please try out and report results, @vyzo!
> segment the memory peerstore + granular locks

- pstoremem/metadata.go
- pstoremem/protobook.go
1. Remove intern limits on protocols. Those only existed because the logic applied to _all_ datastores. As the in-memory datastore doesn't have any form of GC, there's no need to limit interning in any way.
2. Intern specific metadata. The AgentVersion and ProtocolVersion are, in fact, using up quite a bit of memory in long-running machines.
> improve interning

- pstoreds/addr_book.go
- pstoremem/addr_book.go
- test/addr_book_suite.go
The first fix independently extends the address expiration time and the address TTL:
By example:
* We have an address with a TTL of 4s that will expire in 1s.
* We update it with a TTL of 3s.
Before this change:
* We end up with an address with a TTL of 3s that will expire in 3s.
After this change:
* We end up with an address with a TTL of 4s that will expire in 3s.
---
The second fix prevents the in-memory addressbook from announcing existing addresses every time their TTLs get updated.
---
The third fix correctly updates TTLs for existing addresses in the on-disk addressbook.
This fixes https://github.com/libp2p/go-libp2p-identify/issues/2
> fix multiple TTL bugs

- go.mod
- go.sum
- pstoremem/inmem_test.go
- pstoremem/peerstore.go
Reference pstoremem components by pointer to:
1. Avoid copying locks around on construction.
2. Avoid copying these around when calling `weakClose`.
3. Ensures that they all implement the `io.Closer` interface (it's implemented on the pointer, not the value).
Technically, we could have just taken a reference when calling `weakClose`, but this is cleaner.
Also, add a leak test.
> fix: make closing the in-memory peerstore actually close it

- pstoremem/addr_book.go
The `addrs` can very well be nil. However, we should remove the signed peer records entry ONLY if we end up expiring all addresses we Have.
> Fix memory store signed peer record bug

- pstoreds/addr_book.go
- pstoreds/metadata.go
- pstoreds/protobook.go
- pstoremem/addr_book.go
- pstoremem/metadata.go
- pstoremem/protobook.go
- test/peerstore_suite.go
Feels like Java all over again.
fixes #87
> fix: handle nil peer IDs

- go.mod
- go.sum
- pstoreds/protobook.go
- pstoremem/protobook.go
- test/peerstore_suite.go
Implements interface change proposed in https://github.com/libp2p/go-libp2p-core/pull/148.
This PR adds a `SupportsAnyProtocol` API that allows clients to determine if the peer supports ANY of the given protocols without knowing which of the given protocols it actually supports.
> Implement the FirstSupportedProtocol API

- pstoreds/addr_book.go
Record was used without guard.
Was racy with `setAddr`: `pr.Addrs = append(pr.Addrs, entries...)`
> addrbook: fix races

- pstoreds/addr_book.go
- pstoremem/addr_book.go
- test/addr_book_suite.go
1. Previously, two calls to ConsumePeerRecord could interleave and cause us to keep _old_ addresses with a _new_ record. This has only been fixed in the in-memory peerstore.
2. Changes `ConsumePeerRecord` to accept peer records with sequence numbers equal to existing peer records. This lets us update the TTL. Otherwise, we'll never update the TTL for a peer's addresses until they create a new record.
> fix two bugs in signed address handling

- pstoremem/addr_book.go
- test/addr_book_suite.go
1. Fix expiration check to check "not before" instead of after. Otherwise, something that is expiring "now" won't count as expired. The datastore-backed peerstore already had the correct logic.
2. Short-circuit updating the TTL to 0 and just delete the records.
Note: this wasn't causing problems on Linux (likely due to monotonic clocks?) but was causing go-libp2p tests to fail reliably on Windows.
> fix: delete addrs when "updating" them to zero

- pstoremem/addr_book.go
@Stebalien 
Continuation of https://github.com/libp2p/go-libp2p-peerstore/pull/133.
> Only remove records during GC

- pstoreds/ds_test.go
- test/addr_book_suite.go
1. Don't run datastore tests in parallel.
2. Avoid writing to disk, just test in-memory.
3. Add some additional assertions to make debugging errors easier.
> Fix test flakes

- pstoreds/addr_book.go
After recent upgrade to latest libp2p libraries I saw that my app runs 10% cpu in idle. After debugging I found that this function sometimes do 40000*80000 (1-4 billion) iterations. I don't known why it gets so many addresses (on average there is only 10-200 addresses), so I only fix this complexity issue.
> Fix perfomance issue in updating addr book

- pstoreds/keybook.go
This PR removes the deprecated function call to `Bytes()`.
Without that fix, the lib is incompatible with the latest versions of `github.com/libp2p/go-libp2p-core`
> fix: replace deprecated call

- pstoremem/metadata.go
Now that we're garbage collection disconnected peers, the memory usage of saving `N` times the `AgentVersion` and `ProtocolVersion` should be negligible, if `N` is O(1000). Otherwise, we'd also have to implement garbage collection of the `interned` map.
> remove metadata interning

- pstoreds/addr_book.go
- pstoreds/metadata.go
- pstoreds/protobook.go
- pstoremem/addr_book.go
- pstoremem/metadata.go
- pstoremem/protobook.go
- test/peerstore_suite.go
Fixes #182.
To check if this has any unintended consequences, I build a go-ipfs binary where any failed call to `peer.ID.Validate` would panic. I ran it for a few hours without any problems.
> remove all calls to peer.ID.Validate

- pstoremem/protobook.go
> pstoremem: fix slice preallocation in GetProtocols

- pstoremem/addr_book.go
- pstoremem/peerstore.go
Necessary to fix some of the flaky tests in go-libp2p. For example https://github.com/libp2p/go-libp2p/issues/1523 is flaky because we assume that right after we disconnect a peer and check the addrs less than 500ms has elapsed. Of course in a normal environment that's a fine assumption, but in these CI environments relying on things generally happening in a certain amount of time leads to flaky test results.
This also has the added benefit that things don't have to sleep to test the passage of time, they can increment the mock clock. (Didn't update the test suite since I didn't want to update pstoreds version).
> feat: use a clock interface to better support testing for pstoremem

- go.mod
- go.sum
- pstoreds/addr_book.go
- pstoreds/addr_book_gc.go
- pstoreds/addr_book_gc_test.go
- pstoreds/ds_test.go
- pstoreds/peerstore.go
- pstoremem/inmem_test.go
- test/addr_book_suite.go
- version.json
Continues the work from https://github.com/libp2p/go-libp2p-peerstore/pull/199 to do the same thing in pstoreds.
This also updates the tests. On my machine, tests finish in 5s compared to 46s before this change.
> feat: Use a clock interface in pstoreds as well

- pstoremem/addr_book.go
This avoid a lot of unnecessary locking of the mutex. See https://github.com/libp2p/go-libp2p-core/pull/261.
> stop using the peer.Set

- metrics_test.go
> fix flaky EWMA test

- pstoreds/addr_book_gc_test.go
> fix flaky TestGCDelay
